# Generated by Django 5.1.5 on 2025-01-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
    ]
