# Generated by Django 5.1.5 on 2025-01-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.manufacturer'),
        ),
    ]
