# Generated by Django 5.1.5 on 2025-01-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
