# Generated by Django 5.1.5 on 2025-01-28 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_inventory_options_purchasetransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
