# Generated by Django 5.1.5 on 2025-02-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_inventory_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_purchase',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_sale',
            new_name='sale_price',
        ),
    ]
