# Generated by Django 5.1.5 on 2025-02-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_price_purchase_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-expiry_date']},
        ),
        migrations.AlterModelOptions(
            name='purchasedproduct',
            options={'ordering': ['-expiry_date']},
        ),
        migrations.AlterModelOptions(
            name='purchasetransaction',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='updated_at',
        ),
    ]
