# Generated by Django 5.1.5 on 2025-02-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasetransaction',
            options={},
        ),
    ]
