# Generated by Django 5.1.5 on 2025-02-01 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_inventory_options_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasetransaction',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
