# Generated by Django 5.1.5 on 2025-03-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_productcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedproduct',
            old_name='unit_price',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
    ]
