# Generated by Django 5.1.5 on 2025-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_unit_price_purchasedproduct_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'expiry_date'), name='unique_product_expiry'),
        ),
    ]
