# Generated by Django 5.1.5 on 2025-04-11 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_saletransaction_soldproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldproduct',
            options={'ordering': ['-inventory_item__expiry_date']},
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='soldproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.inventory'),
        ),
    ]
