# Generated by Django 5.1.5 on 2025-04-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_soldproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproduct',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.inventory'),
        ),
    ]
