# Generated by Django 5.1.5 on 2025-04-15 11:53

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_soldproduct_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[home.validators.validate_phone_number]),
        ),
    ]
