# Generated by Django 5.1.5 on 2025-06-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
