# Generated by Django 5.1.5 on 2025-06-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_category_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='home.product'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Insurance', 'Insurance')], default='Cash', max_length=20),
        ),
    ]
