# Generated by Django 5.1.5 on 2025-06-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_inventory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
