# Generated by Django 5.1.5 on 2025-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_saletransaction_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Enter percentage, e.g. 10.00 for 10%', max_digits=5)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('products', models.ManyToManyField(related_name='discounts', to='home.product')),
            ],
        ),
    ]
