# Generated by Django 5.1.5 on 2025-07-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_purchasetransaction_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasetransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saletransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='purchasetransaction',
            name='updated_at',
        ),
    ]
