# Generated by Django 5.1.5 on 2025-07-21 17:34

import django.db.models.deletion
import django.utils.timezone
import home.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_purchasetransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchasedproduct',
            options={'ordering': ['-expiry_date'], 'verbose_name': 'Purchased Product', 'verbose_name_plural': 'Purchased Products'},
        ),
        migrations.AlterModelOptions(
            name='purchasetransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase Transaction', 'verbose_name_plural': 'Purchase Transactions'},
        ),
        migrations.AlterModelOptions(
            name='saletransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale Transaction', 'verbose_name_plural': 'Sale Transactions'},
        ),
        migrations.AlterModelOptions(
            name='soldproduct',
            options={'ordering': ['-inventory_item__expiry_date'], 'verbose_name': 'Sold Product', 'verbose_name_plural': 'Sold Products'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Low Stock Threshold'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='Requires Prescription'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[home.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='from_date',
            field=models.DateField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Enter percentage, e.g. 10.00 for 10%', max_digits=5, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(related_name='discounts', to='home.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='to_date',
            field=models.DateField(verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='home.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[home.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='purchase_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='home.purchasetransaction', verbose_name='Purchase Transaction'),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Cash Received'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Insurance', 'Insurance')], default='Cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='transaction_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Transaction Number'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.inventory', verbose_name='Inventory Item'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='sale_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_products', to='home.saletransaction', verbose_name='Sale Transaction'),
        ),
    ]
